### PR TITLE
Develop new site

### PR DESCRIPTION
**Pull request by bsaul**
This is a complete remake of the site.

**This currently release removes the `old-mbbs` pages** from the site. We can decide to keep them, but I'm trying to clean up for now.

## Tasks for initial release

- [x] add `Makefile` And/Or nix build plan
- [ ] update README
- [x] clean up `elm.json`; remove any unneeded dependencies
- [x] #23 
- [x] #26  - interactive species trends
  - [x] ability to toggle route detail on/off
  - [x] make sure the colors for counties for route detail lines and mean lines are the same.
- [x] visualization by functional group
  - [x] ability to select trait to group by
  - [x] place county selection in same place as other controls
- [x] remake sortable/filterable table. See [this package](https://package.elm-lang.org/packages/billstclair/elm-sortable-table/latest/Table) as an option
- [x] UI of visualizations:
   - [x] increase axis label/title font sizes
   - [x] use consistent configurations such as plot sizes etc
   - [x] improve styling around viz controls (more spacing)
   - [x] radio selection for counties control not showing on individual species viz
- [x] optimize and [uglify](https://www.npmjs.com/package/uglify-js )the js
- [x] tooltips are flaky: why are they sometimes working, sometimes not?

## Considering

- [ ] include data prep in build process  
- [ ] ability to toggle trend fit lines on/off for 

## For Later

- [ ] Vizualization UI
   - [ ] make visualizations responsive
   - [ ] use site css theme for colors/fonts/sizes/etc (or at least be consistent)
   - [ ] see that vizs work with dark theme
- [ ] #27 (route dashboard)
- [ ] review efficiency of visualizations
  - [ ] load data from JSON instead of CSV?
  - [x] for individual species split big file into separate per species (as is currently done on live site)

### CODE REVIEW

**Comment by IJBG** [comment]
Orange county's currently red on the results by species page when splitting out by country. As a checkmark under the Interactive Species Trend Explorer checklist, swap Durham and Orange colors?

**Comment by bsaul** [comment]
> Orange county's currently red on the results by species page when splitting out by country. As a checkmark under the Interactive Species Trend Explorer checklist, swap Durham and Orange colors?

I just updated the colors the counties to a) make orange be orange and b) make sure the route detail colors are the same as the average trend.

Let me know what you think.

**Comment by IJBG** [comment]
> > Orange county's currently red on the results by species page when splitting out by country. As a checkmark under the Interactive Species Trend Explorer checklist, swap Durham and Orange colors?
> 
> I just updated the colors the counties to a) make orange be orange and b) make sure the route detail colors are the same as the average trend.
> 
> Let me know what you think.

I like the new colors! That looks great

**Comment by bsaul** [comment]
@IJBG @ahhurlbert to summarize our last meeting:

By end of April, I will:

* update site styling for consistency between site and visualization; bigger axis font size; etc.
* recreate something like [the trend table](https://minibbs.us/species_trends.html) on the current site
* filter out Orange route 11 in 2012 from the visualization data 

On the line, we will see about adding a route "dashboards) (#27) and adding trend lines to appropriate vizualizations.

Am I missing anything?

**Comment by IJBG** [comment]
Been working on updating observers, if we can leave the old site files in the repo I think they're likely to remain useful - I'm going back and referencing them to check things

**Comment by bsaul** [comment]
> Been working on updating observers, if we can leave the old site files in the repo I think they're likely to remain useful - I'm going back and referencing them to check things

Cool. Are you looking at files online or on your local machine?

**Comment by bsaul** [comment]
@ahhurlbert - FYI rather than deal with mixed text/missing/numeric values in the all species table, I simply set the trend to 0 for any species observed in fewer than 6 years. We can do something more elegant later.

**Comment by ahhurlbert** [comment]
Sounds good. But perhaps we can then put a footnote somewhere on the page to that effect?

**Pull request merged**
