### PR TITLE
Route dashboard

### PR DESCRIPTION
**Pull request by bsaul**
Closes:

* #27 
* #48

### CODE REVIEW

**Comment by bsaul** [comment]
@ahhurlbert @IJBG - this is still a WIP but you can see trends by route on the deploy preview: https://deploy-preview-47--cocky-wilson-b55996.netlify.app/results/route-dashboard.html.

**Comment by ahhurlbert** [comment]
Nice start.

Looking at a few patterns reminds me that @IJBG and I were discussing the importance of knowing which years were surveyed by different people when interpreting patterns.

E.g., Orange 4 shows an outlier count in 2011, which is the only year it was surveyed by Tom Driscoll. Orange 11 also shows what is likely to be apparent trends generated by user differences in detection ability over different portions of the time series. Thus for the data viz, it will be useful to color code points and lines of the trajectory by UserID. @IJBG is working on a .csv that will allow us to assign UserID to each route-year.

(Needless to say we need to be pretty skeptical of our trend estimates until we start running models with UserID as random effect, or something similar...)

**Comment by bsaul** [comment]
@IJBG @ahhurlbert - remind me, do we have a google map URL per route?

**Comment by bsaul** [comment]
I've added a species count plot. That you can see in the deploy preview:

https://deploy-preview-47--cocky-wilson-b55996.netlify.app/results/route-dashboard.html

Currently there's only 2 routes that show, as I'm in the process of creating a data type that includes each route's information which we can then display as we want.

**Comment by ahhurlbert** [comment]
Good task for @IJBG -- on the googlemap, zoom into each route so that it fills the screen, and save that coordinate+zoom-specific URL in a table to provide for these purposes

**Comment by bsaul** [comment]
> Good task for @IJBG -- on the googlemap, zoom into each route so that it fills the screen, and save that coordinate+zoom-specific URL in a table to provide for these purposes

@IJBG - I've added the ability to display route maps. See e.g here:https://deploy-preview-47--cocky-wilson-b55996.netlify.app/results/route-dashboard.html. The map displayed for a route is set by the `map` field in `routes/<route>.yaml`. Currently, I have three fields within `map`: 

* `mid`: the map's google ID (I think we only have one map currently but this parameter would allow us to have (e.g) one dedicated map per route.
* `lat`: the latitude  of the center coordinate for the map's display
* `lon`: the longitude of the center coordinate for the map's display

**Comment by bsaul** [comment]
> @IJBG is working on a .csv that will allow us to assign UserID to each route-year.

@IJBG what's the status of this csv file?

**Comment by IJBG** [comment]
Emailing it over now! It'll also be on the observers branch once I switch computers and push some commits

**Comment by bsaul** [comment]
FYI - The preview now has a simple summary table of species observed on a selected route.

**Comment by bsaul** [comment]
Remaining tasks b/f release:

* [ ] add family column to table
* [ ] fix maps
* [ ] add space at bottom of page so that table is not flush against bottom
* [ ] add remaining routes

For later:

* [ ] hover text of column descriptions
* [ ] add observer info to graphs
* [ ] use taxon order in table to be able to sort by taxon order

**Comment by ahhurlbert** [comment]
Just noticed that while the map for Chatham 1 is appropriately centered, the map for Chatham 2 is centered on the same incorrect general area as before (Blands). Thus, there is something still not quite right with the route-specific mapping.
https://deploy-preview-47--cocky-wilson-b55996.netlify.app/results/route-dashboard

**Comment by bsaul** [comment]
@ahhurlbert @IJBG - I think this PR is ready except for adding the configuration file for each route, which is kinda a manual copy/paste process.  I'll chip away at this this week, but if y'all have any time you can see what needs to be done in the `routes` directory (on this branch). Basically, each route needs to have an associated `.yaml` file and I've been copying the information from the respective route page.

**Comment by bsaul** [comment]
@ahhurlbert @IJBG - I'm going to go ahead and merge the route dashboard to make this feature live, but please open an issue/let me know if see any bugs. 

Also feel free to add to #55 with additional features and other updates we should make.

**Pull request merged**
